// ============================================================
// js/70n-sicily.ts — events for Sicilian Solfifera Series
// ============================================================
// Cianciana / Caltanissetta district, Agrigento province, Sicily.
// Messinian (6-5.3 Ma) sedimentary native-sulfur deposit hosted in
// the Solfifera Series — the gypsum+marl sequence laid down during
// the Mediterranean salinity crisis. The world's primary sulfur
// production center 1860s-1950s; the canonical sedimentary BSR
// native-sulfur deposit type.
//
// Mechanism (Ziegenbalg et al. 2010 Sedimentary Geology; Manzi
// et al. 2009 Sedimentary Geology; Decima & Wezel 1971):
//   1. Messinian gypsum (CaSO₄·2H₂O) precipitated in the Sicilian
//      basin during the 6-5.3 Ma salinity crisis.
//   2. Anaerobic bacterial sulfate reduction (BSR) at depth used
//      the gypsum sulfate as electron acceptor:
//        CaSO₄ + 2 CH₂O (organic-C) → CaS + 2 H₂CO₃
//      H₂S accumulates in the gypsum-marl horizon. Some BSR-mediated
//      microorganisms also directly precipitate S° in the basin
//      sediment (the bacterial-disproportionation pathway).
//   3. Pleistocene meteoric water infiltrates the upper few meters
//      of the section, carrying dissolved atmospheric O₂.
//   4. H₂S from below meets O₂ from above → synproportionation
//      H₂S + ½O₂ → S° + H₂O — precipitates the mineable native
//      sulfur in the upper oxidation zone (top ~5 m of section).
//   5. Co-products: calcite cement (from CaCO₃ generated by step 2),
//      residual gypsum (selenite), celestine where Sr is available.
//
// Engine fit: the v80 native_sulfur engine has a bimodal pH factor
// with peaks at 2.5 (Sulphur-Bank acid-sulfate) and 6.0 (Sicilian
// BSR-near-surface). The pH ≤ 6.5 cap admits Sicilian fluid; the
// O₂ ∈ [0.1, 0.7] window admits the mixed-oxic infiltration zone.
// Engine fires unchanged by THIS commit; the v80 engine change
// landed alongside this scenario.
//
// 4 handlers — gypsum dissolution, meteoric O₂ infiltration,
// carbonate buffering, late S° precipitation pulse.

function event_sicily_gypsum_dissolution(c) {
  // Meteoric water dissolves the encasing Messinian gypsum
  // (CaSO₄·2H₂O), releasing Ca²⁺ + SO₄²⁻ into the porewater. SO₄
  // is the upstream substrate that BSR converts to H₂S; we add it
  // as fluid.S (the fluid-chemistry abstraction conflates oxidation
  // states). Mild pH increase from the dissolution (saturating
  // toward 7.5 the calcite-gypsum equilibrium point).
  c.fluid.Ca += 200;
  c.fluid.S += 100;
  c.fluid.Sr += 5;             // Messinian gypsum carries 1-3% Sr; celestine signature
  c.fluid.pH = Math.min(6.5, c.fluid.pH + 0.3);
  c.flow_rate = 0.4;
  return `Meteoric water dissolves Messinian gypsum: Ca rises to ${c.fluid.Ca.toFixed(0)} ppm, S to ${c.fluid.S.toFixed(0)} ppm. Sr trace boost for celestine. Carbonate equilibrium pulls pH toward ${c.fluid.pH.toFixed(1)}.`;
}

function event_sicily_meteoric_o2_pulse(c) {
  // Pleistocene meteoric water infiltrates the upper section. O₂
  // pins to 0.40 — the synproportionation peak. This is what
  // triggers the BSR-produced H₂S to convert to S° in the upper
  // oxidation zone.
  c.fluid.O2 = 0.40;
  // Some sulfide consumed as it converts to elemental S°. Slight
  // acidification from the local H₂SO₄ byproduct (synproportionation
  // is mass-conservative for S but releases H⁺).
  c.fluid.pH = Math.max(5.5, c.fluid.pH - 0.2);
  c.flow_rate = 0.5;
  return `Pleistocene meteoric water arrives — O₂ pins to ${c.fluid.O2.toFixed(2)} at the BSR-oxidation interface. H₂S from depth meets O₂ from above → S° precipitates. pH drifts to ${c.fluid.pH.toFixed(1)}.`;
}

function event_sicily_carbonate_buffer(c) {
  // BSR-generated H₂CO₃ + carbonate-buffered porewater stabilizes pH
  // around 6.0 — the peak of the engine's BSR-mode ph_f factor.
  // CO₃ accumulates from BSR's organic-C oxidation; Ca holds steady
  // from gypsum dissolution.
  c.fluid.CO3 += 60;
  c.fluid.pH = 6.0;
  c.flow_rate = 0.2;
  return `BSR-generated H₂CO₃ buffers the porewater. CO₃ rises to ${c.fluid.CO3.toFixed(0)} ppm; pH pinned at 6.0 — the peak of the engine's BSR-mode pH factor. Calcite cement starts to precipitate.`;
}

function event_sicily_late_synproportionation(c) {
  // Late-stage synproportionation event: fresh O₂-rich meteoric
  // pulse + still-high S substrate from the BSR reservoir below.
  // The geological story: even after millions of years of slow BSR,
  // the H₂S pool stays replenished as long as gypsum remains.
  c.fluid.S += 80;
  c.fluid.O2 = 0.45;             // slightly above peak — late synprop slightly excess-O₂
  c.fluid.pH = Math.max(5.8, c.fluid.pH - 0.1);
  c.flow_rate = 0.3;
  return `Late synproportionation event — fresh O₂ pulse meets the still-replenished H₂S pool from below. S rises to ${c.fluid.S.toFixed(0)} ppm. Native sulfur continues to grow in the upper oxidation zone.`;
}
