#!/usr/bin/env node
/**
 * tools/build.mjs — concatenate js/**\/*.js into the inline <script> block of index.html.
 *
 * Phase B1 of PROPOSAL-MODULAR-REFACTOR. The shipped product (index.html)
 * stays a single file so file:// "open and play" keeps working. The
 * source-of-truth lives under js/, sorted lexicographically by path.
 * Naming convention: `00-`, `10-`, `20-`, … prefixes preserve order.
 *
 * Usage:
 *   node tools/build.mjs           # rebuild index.html from js/
 *   node tools/build.mjs --check   # exit 1 if rebuild would change index.html
 *
 * Markers in index.html:
 *   // === BUILD:bundle:start ===
 *   …concatenated content…
 *   // === BUILD:bundle:end ===
 *
 * Add a new module by dropping a .js file under js/ — its load order is
 * determined entirely by where it sorts lexicographically among siblings.
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const JS_DIR = join(ROOT, "js");
const INDEX = join(ROOT, "index.html");
const START_MARKER = "// === BUILD:bundle:start ===";
const END_MARKER = "// === BUILD:bundle:end ===";

function walkSorted(dir) {
  const out = [];
  const stack = [dir];
  while (stack.length) {
    const d = stack.pop();
    let entries;
    try {
      entries = readdirSync(d).sort();
    } catch {
      continue;
    }
    for (const name of entries) {
      if (name.startsWith(".")) continue;
      const p = join(d, name);
      const st = statSync(p);
      if (st.isDirectory()) stack.push(p);
      else if (name.endsWith(".js")) out.push(p);
    }
  }
  // Re-sort by full relative path so directory traversal order doesn't matter.
  return out.sort((a, b) =>
    relative(JS_DIR, a).split(sep).join("/").localeCompare(
      relative(JS_DIR, b).split(sep).join("/")
    )
  );
}

function concatModules(files) {
  const parts = [];
  for (const f of files) {
    const rel = relative(JS_DIR, f).split(sep).join("/");
    parts.push(`// ── ${rel} ──`);
    parts.push(readFileSync(f, "utf8").replace(/\s+$/, ""));
  }
  return parts.join("\n\n");
}

function rebuild(html, body) {
  const i = html.indexOf(START_MARKER);
  const j = html.indexOf(END_MARKER);
  if (i < 0 || j < 0) {
    throw new Error(
      `index.html is missing build markers. Add\n  ${START_MARKER}\n  ${END_MARKER}\ninside the <script> block.`
    );
  }
  // Preserve exactly one newline after the start marker line and one before the end marker line.
  const startLineEnd = html.indexOf("\n", i);
  const endLineStart = html.lastIndexOf("\n", j) + 1;
  return (
    html.slice(0, startLineEnd + 1) +
    "// auto-generated by tools/build.mjs from js/**/*.js — edit those files, not this block\n\n" +
    body +
    "\n\n" +
    html.slice(endLineStart)
  );
}

const files = walkSorted(JS_DIR);
if (!files.length) {
  console.error("[build] no .js files found under js/");
  process.exit(1);
}

const html = readFileSync(INDEX, "utf8");
const body = concatModules(files);
const next = rebuild(html, body);

if (process.argv.includes("--check")) {
  if (next !== html) {
    console.error(
      `[build] index.html is out of date — run \`node tools/build.mjs\` to regenerate.\n        diff length: ${Math.abs(next.length - html.length)} chars`
    );
    process.exit(1);
  }
  console.log(`[build] index.html is up to date with ${files.length} module(s)`);
  process.exit(0);
}

writeFileSync(INDEX, next);
console.log(
  `[build] rebuilt index.html from ${files.length} module(s) (${body.length.toLocaleString()} chars)`
);
